### ISSUE TITLE
.close() type conflict

### ISSUE THREAD

**Issue by v1rtl** [denosaurs/event#1]
Hello!

I'm working on [node_http](https://github.com/deno-libs/node-http), a Node.js-like HTTP server and I need to implement `Server.close()` method. However, `EventEmitter` already contains `.close()` method.

My suggestion would be renaming `.close()` to `removeAllListeners()`

ref: https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_emitter_removealllisteners_eventname

**Comment by crowlKats** [comment]
`close` is different from `off` (which is the equivalent of `removeAllListeners` when no args are passed). I agree the name for `close` should be changed though, or maybe `close` be merged into `off`

**Comment by crowlKats** [comment]
Fixed in 125dc6f3de085ecdad26d02a379e205495813359
